#docker run --name mysql-container -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=student_management -v C:\Users\locht\Project\Database\MySQL:/var/lib/mysql -d -p 3306:3306 mysql:latest
server:
  port: 3000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_management
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC

jwt:
  secret: your_secret_key_should_be_long_enough_123456
  expiration: 86400000 # 1 ngày (ms)
  refresh-threshold: 86400000 # 1 ngày (ms)

